package:
  name: vlfeat
  version: "0.9.20"

source:
  fn: vlfeat-0.9.20-bin.tar.gz
  url: http://www.vlfeat.org/download/vlfeat-0.9.20-bin.tar.gz
  sha1: 1aa063af825b28dca332396732268e98f4821179

  patches:
    - no_crt_copy.patch    # [win]
    - no_snprintf.patch    # [win and py35]
    - vs2010_openmp.patch  # [win and py34]
    - vs2010_path.patch    # [win and py34]
    - no_test.patch        # [unix]

build:
  number: 1
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - vcomp   # [win]

  run:
    - vcomp   # [win]

test:
  requires:
    - python                                              # [win]

  commands:
    - sift -h
    - mser -h
    - aib -h
    - if not exist %PREFIX%\\Library\\bin\\vl.dll exit 1  # [win]
    - test -f $PREFIX/lib/libvl.dylib                     # [osx]
    - test -f $PREFIX/lib/libvl.so                        # [linux]

about:
  home: http://www.vlfeat.org/
  summary: The VLFeat open source library implements popular computer vision algorithms specializing in image understanding and local features extraction and matching.
  license: BSD 2-Clause
